arfima_model = arfima(df$Close)
arfima_forecast = forecast(arfima_model, h=12)
plot(arfima_forecast)
summary(arfima_model)
hurstexp(df$Close)
checkresiduals(arfima_model)
jarque.bera.test(arfima_model$residuals)
shapiro.test(arfima_model$residuals)
Box.test(arfima_model$residuals, type = "Box-Pierce")
Box.test(arfima_model$residuals, type = "Ljung-Box")
white.test(arfima_model$residuals)
